#!/bin/bash

if [ "$1" == "" ] ; then
    echo "Usage: $0 ProjectName"
    exit 1
fi

renamed=$(echo $1 | perl -pne 's/ //g;')
mkdir $renamed
if [ "$?" != "0" ] ; then
    echo "Can't make directory ${renamed}"
    exit 1
fi

cd $renamed

mkdir -p src/{main,test}/{java,resources,scala}
mkdir lib project target


# Create the initial build.sbt file
version=$(echo $SCALA_VERSION | perl -pne 's/^\d+\.(\d+)\.\d+/$1/g;')

if [[ "$version" -le 10 ]] ; then
    SCALA_TEST_STR="\"org.scalatest\" % \"scalatest_2.10\" % \"2.0\" % \"test\""
else
    SCALA_TEST_STR="\"org.scalatest\" % \"scalatest_2.11\" % \"2.2.4\" % \"test\""
fi


# echo "name := \"$1\"
# version := \"1.0\"
# scalaVersion := \"$SCALA_VERSION\"
# libraryDependencies += ${SCALA_TEST_STR}
# " > build.sbt

echo '
buildscript {
    dependencies {
        classpath "com.android.tools.build:gradle:1.2.3"
        classpath "jp.leafytree.gradle:gradle-android-scala-plugin:1.4"
    }
}

apply plugin: "com.android.application"
apply plugin: "jp.leafytree.android-scala"


dependencies {
    compile "org.scala-lang:scala-library:2.11.0"
}

android {
    sourceSets {

    }
}


' > build.gradle



