#!/bin/bash

declare -r TRUE=0
declare -r FALSE=1

function isYes() {
  local x=$1
  [ $x = "y" ] && echo $TRUE; return
  [ $x = "Y" ] && echo $TRUE; return
  [ $x = "yes" ] && echo $TRUE; return
echo $FALSE
}

while [ $TRUE ]; do

    echo ""
    read -p "Directory/Project Name (MyFirstProject): " directoryName
    directoryName=${directoryName:-MyFirstProject}

    read -p "Create .gitignore File? (Y/n): " createGitignore
    createGitignore=${createGitignore:-y}

    read -p "Create README.md File? (Y/n): " createReadme
    createReadme=${createReadme:-y}

    read -p "Organization [com.example] " ORGANIZATION
    ORGANIZATION=${ORGANIZATION:-com.example}

    read -p "Package name [${ORGANIZATION}.app]" PACKAGE
    PACKAGE=${PACKAGE:-"${ORGANIZATION}.app"}

    echo ""
    echo "-----------------------------------------------"
    echo "Directory/Project Name: $directoryName"
    echo "Create .gitignore File?: $createGitignore"
    echo "Create README.md File?: $createReadme"
    echo "-----------------------------------------------"
    read -p "Create Project? (Y/n): " createProject
    createProject=${createProject:-y}
    [ "$(isYes $createProject)" = "$TRUE" ] && break

done

mkdir -p ${directoryName}/src/{main,test}/{java,resources,scala}
mkdir ${directoryName}/lib ${directoryName}/project ${directoryName}/target

mkdir -p ${directoryName}/src/main/config
mkdir -p ${directoryName}/src/{main,test}/{filters,assembly}
mkdir -p ${directoryName}/src/site

# Create the initial build.sbt file
version=$(echo $SCALA_VERSION | perl -pne 's/^\d+\.(\d+)\.\d+/$1/g;')

if [[ "$version" -le 10 ]] ; then
    SCALA_TEST_STR="\"org.scalatest\" % \"scalatest_2.10\" % \"2.0\" % \"test\""
else
    SCALA_TEST_STR="\"org.scalatest\" % \"scalatest_2.11\" % \"2.2.4\" % \"test\""
fi

if [[ -z ${SCALA_VERSION} ]] ; then
    SCALA_VER_STRING="scalaVersion := \"2.11.0\""
else
    SCALA_VER_STRING="scalaVersion := \"${SCALA_VERSION}\"

scalaHome := Some(file(\"${SCALA_HOME}\"))"
fi


echo "name := \"${PACKAGE}\"

version := \"1.0\"

${SCALA_VER_STRING}

organization := \"${ORGANIZATION}\"

libraryDependencies += ${SCALA_TEST_STR}

" > ${directoryName}/build.sbt

#------------------------------
# create .gitignore, if desired
#------------------------------
if [ "$(isYes $createGitignore)" = "$TRUE" ]; then
echo "bin/
project/
target/
.cache
.classpath
.project
.settings" > ${directoryName}/.gitignore
fi

#-----------------------------
# create README.me, if desired
#-----------------------------
if [ "$(isYes $createReadme)" = "$TRUE" ]; then
touch ${directoryName}/README.md
fi

echo -ne "

package ${PACKAGE}


object Main extends App { 
   println(\"Hello SBT\") 
}

" > ${directoryName}/src/main/scala/hellosbt.scala
