#!/usr/bin/perl

use File::Temp qw(tempfile);

my ($fh ,$file) = tempfile();
open(CMD, "|gnuchess -g -q | perl -ne 'if( !/^(GNU|White|Time|^ +|^ *\$)/ ) { print; }'");
if ( ! -f $ARGV[0]) {
    $ff = $file;
    print $fh "$ARGV[0]\n";
} else {
    while(<>) {
        chomp;
        if ( -f $_ ) {
            #print CMD "epdload ${_}\nexit\n";
            $ff = $_;
        } else {
            chomp;
            print $fh "$_\n";
            # close($fh);
            # print CMD "epdload ${file}\nexit\n";
            $ff = ${file}
        }
        last;
    }
}
close($fh);
print CMD "epdload ${ff}\nexit\n";

close(CMD);
