#!/usr/bin/perl

use File::Temp qw(tempfile);

my @fens;

for(my $i=0; $i<=$#ARGV ; $i ++ ) {
    if ( ! -f $ARGV[$i] ) {
        push( @fens,splice( @ARGV,$i,1 ));
        $i --;
    } else {
        push( @fens, map {chomp; $_; } $ARGV[$i] );
    }
}
# sub show_fen($) { 
#     my $fh = shift;
#     open(CMD, "|gnuchess -g -q | perl -ne 'if( !/^(GNU|White|Time|^ +|^ *\$)/ ) { print; }'");
#     if ( -f $_ ) {
#         print CMD "epdload ${_}\nexit\n";
#     } else {
#         chomp;
#         print $fh "$_\n";
#         close($fh);
#         print CMD "epdload ${file}\nexit\n";
#     }
#     last;
#     close(CMD);
# }
# while(<>) {
#     my ($fh ,$file) = tempfile();
#     show_fen( $fh );
#     close($fh);
# }
# foreach (@fens) {
#         my ($fh ,$file) = tempfile();
#     show_fen( $fh );
#     close($fh);
# }
# while(<>) {

foreach (@fens) {
    chomp;
    my ($fh ,$file) = tempfile();
    open(CMD, "|gnuchess -g -q | perl -ne 'if( !/^(GNU|White|Time|^ +|^ *\$)/ ) { print; }'");
    if ( -f $_ ) {
        print CMD "epdload ${_}\nexit\n";

    } else {
        chomp;
        print $fh "$_\n";
        close($fh);
        print CMD "epdload ${file}\nexit\n";
    }
    close(CMD);
}
